### ISSUE TITLE
CTD with TFC console command

### ISSUE THREAD

**Issue by GiraPomba** [ArranzCNL/ImprovedCameraSE#104] opened 2023-03-23 02:04 UTC
When the game is saved with TFC console command enabled and then loaded (from desktop), the game CTD.
Probably something silly I'm doing, but thought you should know about it.

[https://pastebin.com/4Pik4937](https://pastebin.com/4Pik4937)

**Comment by ArranzCNL** [comment] 2023-03-23 02:48
Confirmed.

I didn't crash but ended up in the middle of nowhere, also entering tfc from first person does the same thing it seems.

**Comment by ArranzCNL** [comment] 2023-03-23 11:38
Upon further investigation it isn't Improved Camera causing this, however I've only recently installed additional mods so I should be able to track down the one causing the problem!

**Comment by GiraPomba** [comment] 2023-03-23 11:42
Probably something in my load order or a change in my settings then, but it happened when loading from desktop and on saves with TFC. Didn't happen with loading whille the game was already opened.

**Comment by ArranzCNL** [comment] 2023-03-23 12:15
It is really weird I just created a brand new game without Improved Camera installed.

1. Enter first person and type tfc
2. Move around and save whilst in tfc
3. Enjoy the picture :D
![tfc_busted](https://user-images.githubusercontent.com/52199624/227199617-d54c1c4a-4053-452a-97d2-e6aa8c552934.png)
I can see why you would have crashed. Fun fact if you don't crash and re-type tfc everything seems normal until you try using tfc again whilst in first person goes back to the same position as in the screenshot.

Going to close the issue as it's not a bug with IC, could be an engine bug I will carry out some more tests with this later.

**Closed as completed by ArranzCNL** 2023-03-23 12:15 UTC
Labels: not a bug

**Comment by ArranzCNL** [comment] 2023-03-23 12:48
Engine bug.

I was able to reproduce with the steps I mentioned above with no mods loaded at all barring skse 2.0.20.

**Moral of the story do not enter tfc in first person I guess as it can corrupt your saves!**

New screenshot completely unmodded taken from 1.6.640 following the reproducable steps above:
![ScreenShot42](https://user-images.githubusercontent.com/52199624/227237102-d2582b55-d1e1-48b2-bc5b-85ae58ac6546.png)

**Comment by GiraPomba** [comment] 2023-03-24 01:30
Thanks for checking. Pretty funny bug.
TFC shouldn't happen in a normal game anyway.

I was testing some mods with Improved camera and in third person view using TFC, saving and reloading a lot of times.

**Comment by ArranzCNL** [comment] 2023-03-24 12:48
I did speak to KernalsEgg about it and we basically came to the conclusion it isn't really something to fix although a bug. It is a very peculiar to save the game whilst tfc is active. Our countless testing between both of us we didn't crash just messed up view upon entering the new save and tfc restored everything back to normal. I do have a corrupt save somehow though (could be a mod in my loadorder causing it) whenever I enter first person and tfc I instantly get sent to 0 0 0.

[FreeFlyCam](https://www.patreon.com/posts/ae-freeflycamae-70012838) does fix this but has issues with current Improved Camera release and no doubt will with the upcoming NG release. Can be resolved with iHookInput=0 and MenuMode=1 or 0.
