### ISSUE TITLE
Meshes & texture in game's map cant be rendered correctly

### ISSUE THREAD

**Issue by Lurker1011** [ArranzCNL/ImprovedCameraSE#3] opened 2022-06-19 08:51 UTC
Description:

--try to uninstall all the mods about Visuals&Graphics (include ENB) , but nothing changed

--Disable the ImprevedCamera DLL can fix it 

![issue](https://github.com/Lurker1011/Image/blob/main/The%20Elder%20Scrolls%20V%20Skyrim%20Special%20Edition_2022.06.19-16.04.png?raw=true)

When i open a menu in Map , the issue is gone
![after open a menu](https://github.com/Lurker1011/Image/blob/main/The%20Elder%20Scrolls%20V%20Skyrim%20Special%20Edition_2022.06.19-16.05.png?raw=true)

or just open the console

![after open console](https://github.com/Lurker1011/Image/blob/main/The%20Elder%20Scrolls%20V%20Skyrim%20Special%20Edition_2022.06.19-16.07.png?raw=true)

openning any menu and console can fix Water opaque issue `https://github.com/ArranzCNL/ImprovedCameraSE/issues/2`

**Comment by ArranzCNL** [comment] 2022-06-19 11:08
Shall investigate and fix, as we only handled the Tween Menu currently. Map Menu obviously needs handling.

Thanks for the report!

**Comment by TwistedModding** [comment] 2022-06-19 15:24
I think this is fixed by disabling fov override

**Comment by ArranzCNL** [comment] 2022-06-19 15:37
Thanks for the report.

Fixed the issue, shall be released today or tomorrow.
I'll close this when it is released.

**Comment by Lurker1011** [comment] 2022-06-20 06:55
> 

 disabling fov override dont work, is it also happen in your game? if it just happen in my game, i guess there maybe something uncompatible with Bug fix mods, i installed Engine fixes, actor limit fix  powerothree's tweaks,  mfgfix  ,modern brawl bug fix and USSEP

**Comment by ArranzCNL** [comment] 2022-06-20 09:48
Changing FOV doesn't seem to do anything looked at that myself, just bringing up the console does as it shuts down UpdateCamera.

The issue is with Improved Camera it is fixed, but you have to wait for PR 2.

**Comment by ArranzCNL** [comment] 2022-06-22 14:06
PR 2 being released later on today.

**Closed as completed by ArranzCNL** 2022-06-22 14:06 UTC
Labels: bug
