### ISSUE TITLE
Not working with 1.6.640

### ISSUE THREAD

**Issue by omaya01** [ArranzCNL/ImprovedCameraSE#60] opened 2022-12-04 18:19 UTC
When I try to open the game from skse64_launcher a window pops up saying that this mod is not compatible with 1.6.640 and needs to be updated. I installed the 1.6.x version (ofc).

**Comment by noughtmare** [comment] 2022-12-04 19:34
Duplicate of #42

**Closed as completed by noughtmare** 2022-12-04 19:34 UTC
