### ISSUE TITLE
SKSE: Not compatible with 1.6.640

### ISSUE THREAD

**Issue by Tenurian** [ArranzCNL/ImprovedCameraSE#50] opened 2022-11-01 04:22 UTC
Hey there, I'm trying to get the ImprovedCameraAE working and SKSE keeps telling me it's not compatible with my version of the game (1.6.640.0) and only works with versions 1.6.629 and earlier. I saw there were a few downgrade tools, but none of them seem to get me to 1.6.XXX below that range. Are there any plans to get ICSE working with Skyrim versions >= 1.6.640?

Uploading the full SKSE error message for context.
![ICSE Error Message](https://user-images.githubusercontent.com/10442031/199158054-b6af9909-4237-4d4f-b17e-877ff6c2336b.PNG)

**Comment by noughtmare** [comment] 2022-11-01 06:39
Duplicate of #42

**Closed as completed by noughtmare** 2022-11-01 06:39 UTC

**Comment by noughtmare** [comment] 2022-11-01 06:42
There is a downgrade patcher, e.g. BestOfBoth_1.6.640.0-1.6.353.0.exe on this page: https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files&file%5C_id=316281. We don't really support 1.6.629 either as far as I know, so 1.6.353 is a safer bet. 353 is also the version of 1.6 that the most mods are compatible with.

**Comment by Tenurian** [comment] 2022-11-02 03:27
Alrighty. Downgrading causes issues with some of the newer mods I have and want to keep, so I'll just run Joy of Perspective for now until the 1.6.640 update for ICSE is out. Also, thank you for providing the first issue request for this, subscribed to it now so I'll be able to keep up with development and know when the new version is out!
